# Generated by Django 5.2.1 on 2025-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
