# Generated by Django 5.2.1 on 2025-05-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
